name = "modfest 1.15"
author = "LemmaEOF"
version = "1.0.0+modrinth_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "270150d8155cb4b6eb2e01a77da6ca055224edd3f86166f9f539c4e32f00b488"

[versions]
fabric = "0.8.2+build.194"
minecraft = "1.15.2"
